
development:
  adapter: mysql2
  database: ymyw_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: ymyw_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: ymyw_production
  username: root
  password: 
  encoding: utf8

